name: Check Local Runner

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Check Docker
        run: docker version

      - name: Check Docker Compose
        run: docker compose version

      - name: Check Runner
        run: whoami